### ISSUE TITLE
Support box or nonnegativity constraints?

### ISSUE THREAD

**Issue by tomwenseleers** [jasonge27/picasso#10]
Would it be possible for picasso in the future to also support box constraints on the fitted coefficients by any chance, similar to what glmnet can do using arguments lower.limits and upper.limits? E.g. to support nonnegativity constraints?

**Comment by jasonge27** [comment]
A staightforward implementation is to add the clipping mechanism in the coordinate_descent function implemented in objective function classes [https://github.com/jasonge27/picasso/blob/f4b6a10a5f3e1dbc6797a636d425658563450a9b/src/objective/glm.cpp#L24](url). I am not sure if clipping works well in terms of stability and accuracy of the algorithm. We will test this implementation in the future. Pull request is highly welcome!
