### ISSUE TITLE
Link scale for Poisson models?

### ISSUE THREAD

**Issue by tomwenseleers** [jasonge27/picasso#11]
I was wondering what link scale is assumed for Poisson models? Is this a log link? If so, I was wondering if it would be hard to also support Poisson models with an identity link? I am asking because I am dealing with models where my noise is Poisson but where my covariates act additively rather than multiplicatively...

**Comment by jasonge27** [comment]
Yes, we used standard log link for Poisson model. To use customized link function, we can follow the two-step process
1. Implement a new subclass for class GLMObjective (see include/picasso/objective.hpp and src/objective/glm.cpp).  
2. Add a new function in the c interface in /src/c_api/c_api.cpp. With this new objective function class, you can pass it to the standard ActNewton solver for the computation (same with  [https://github.com/jasonge27/picasso/blob/f4b6a10a5f3e1dbc6797a636d425658563450a9b/src/c_api/c_api.cpp#L166-L170](url)
Pull request highly welcome!
