### ISSUE TITLE
Threshold operator of MCP Reg

### ISSUE THREAD

**Issue by HMJiangGatech** [jasonge27/picasso#13]
In https://github.com/jasonge27/picasso/blob/10ba0070199a3e736539fe03e9ea0688f2613e30/include/picasso/objective.hpp#L92-L103

Shouldn't it be like this:
`double soft_thresh_mcp(double y, double lamb, double gamma){
    
    if(fabs(y)>fabs(gamma*lamb)) {
        return y;
    }else{
        return soft_thresh_l1(y, lamb)/(1-1/gamma);
    }
}`

**Comment by jasonge27** [comment]
Thanks for pointing out the bug! Can you do a pull request @HMJiangGatech ? I will merge here on master branch. Thank you!
